- endpoints:
    - "http://api.iobroker.homelab.local/set/hmip.0.devices.3014F711A00001DD8993E517.channels.1.on?value=true"
  cronjobs:
    - "0 4 * * *"
    - "0 9 * * *"

- endpoints:
    - "http://api.iobroker.homelab.local/set/hmip.0.devices.3014F711A00001DD8993E517.channels.1.on?value=false"
  cronjobs:
    - "0 6 * * *"
    - "0 22 * * *"