- endpoints:
    - "http://api.iobroker.homelab.local/set/0_userdata.0.test?value=true"
  cronjobs:
    - "@every 1s"

- endpoints:
    - "http://api.iobroker.homelab.local/set/0_userdata.0.test?value=false"
  cronjobs:
    - "@every 10s"