name: release
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    container: smartive/semantic-release-image:latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install semantic-release/github
        run: npm install semantic-release @semantic-release/github
      - name: semantic-release
        run: semantic-release